version: '3'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-reload-bot
    restart: unless-stopped
    volumes:
      - ./:/app
      - ${EXTERNAL_SCRIPTS_PATH:-/path/to/external/scripts}:/external_scripts
    environment:
      - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
      - RELOAD_SCRIPT_PATH=/external_scripts/up.sh
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge